// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['app']['App']['CloseWindow']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function RegisterGlobalHotkey(arg1) {
  return window['go']['app']['App']['RegisterGlobalHotkey'](arg1);
}
